package com.koncle.imagemanagement.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.koncle.imagemanagement.bean.ImageAndEvent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IMAGE_AND_EVENT".
*/
public class ImageAndEventDao extends AbstractDao<ImageAndEvent, Long> {

    public static final String TABLENAME = "IMAGE_AND_EVENT";

    /**
     * Properties of entity ImageAndEvent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Event_id = new Property(1, Long.class, "event_id", false, "EVENT_ID");
        public final static Property Image_id = new Property(2, Long.class, "image_id", false, "IMAGE_ID");
    }


    public ImageAndEventDao(DaoConfig config) {
        super(config);
    }
    
    public ImageAndEventDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IMAGE_AND_EVENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"EVENT_ID\" INTEGER NOT NULL ," + // 1: event_id
                "\"IMAGE_ID\" INTEGER NOT NULL );"); // 2: image_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IMAGE_AND_EVENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ImageAndEvent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getEvent_id());
        stmt.bindLong(3, entity.getImage_id());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ImageAndEvent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getEvent_id());
        stmt.bindLong(3, entity.getImage_id());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ImageAndEvent readEntity(Cursor cursor, int offset) {
        ImageAndEvent entity = new ImageAndEvent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // event_id
            cursor.getLong(offset + 2) // image_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ImageAndEvent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEvent_id(cursor.getLong(offset + 1));
        entity.setImage_id(cursor.getLong(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ImageAndEvent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ImageAndEvent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ImageAndEvent entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
